# -*- coding: utf-8 -*-
"""Geek-ex1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T6kxKAKgT70f3iOfAOWzmze_1YMoC-HC
"""

import ipywidgets as widgets
from IPython.display import clear_output
import math
import time

class Agente:
  x = 0
  y = 0
  angulo = 0

  def __init__(self, out,x=0, y=0, angulo=0, emoticon="&#128028;"):
    self.x = x
    self.y = y
    self.angulo = angulo
    self.emoticon=emoticon
    self.angulo = angulo
    self.tamanoEmoticon = 20
    
    self.out = out
    self.out.value = "comenzando..."

  def avanzar(self, pasos=1):
    angulo_rad = math.radians(self.angulo)
    delta_x = pasos * math.cos(angulo_rad)
    delta_y = pasos * math.sin(angulo_rad)
    self.x = self.x + delta_x
    self.y = self.y + delta_y
    self.dibujar()
  
  def rotar(self, angulo):
    self.angulo = self.angulo + angulo
    self.dibujar()

  def dibujar(self):
    angulo_dibujo = self.angulo + 135
    self.out.value=f"<div style='width: 150px; height: 150px; border: solid'></div><div style='position: absolute;left: {self.x}px; top: {self.y}px;transform: rotate({angulo_dibujo}deg);font-size:{self.tamanoEmoticon}px;'>{self.emoticon}</div>"
    time.sleep(0.5)

def ejecutar(agente, acciones, valores):
  for i in range(len(acciones)):

      if acciones[i] == "avanzar":
        agente.avanzar(valores[i])

      if acciones[i] == "rotar":
        agente.rotar(valores[i])

def dibujar_ambiente():
  out = widgets.HTML()
  display(out)
  return out

"""
out = dibujar_ambiente()
acciones = ["rotar", "avanzar", "avanzar", "rotar"]
valores = [0, 15, 5, 90]
agente = Agente(out=out, x=50, y=50, angulo=180)

ejecutar(agente, acciones, valores)
"""



